# Back Propagation
### Classification

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/Unstopable18/Datasets/main/student-placement.csv')
df.head()

cgpa     iq  placement
0   6.8  123.0          1
1   5.9  106.0          0
2   5.3  121.0          0
3   7.4  132.0          1
4   5.8  142.0          0

In [5]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)         
    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    return parameters

def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    return A

def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    A = sigmoid(Z)
    return A
    
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2  # number of layers in the neural network   
    for l in range(1, L+1):
        A_prev = A 
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        #print("A"+str(l-1)+": ", A_prev)
        #print("W"+str(l)+": ", Wl)
        #print("b"+str(l)+": ", bl)
        #print("--"*20)
        A = linear_forward(A_prev, Wl, bl)
        #print("A"+str(l)+": ", A)
        #print("**"*20)           
    return A,A_prev

def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [6]:
# epochs implementation

# Parameter initialization
#here, [2,2,1]=[no of features Entry,Activation layer 1 nodes,output layer nodes]
#------------------> (since, here we have only one hidden layer = Activation layer 1)
parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'iq']].values[j].reshape(2,1) #Shape(no of features, no. of training example)
    y = df[['placement']].values[j][0]

    y_hat,A1 = L_layer_forward(X,parameters) #Forward Propagation
    y_hat = y_hat[0][0] #Get y_hat value

    update_parameters(parameters,y,y_hat,A1,X) #Gradient Descent to update weights and biases

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat)) #Calculate loss BCE

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean()) #Calculate Avg loss for epoch

parameters

Epoch -  1 Loss -  0.7047541601778821
Epoch -  2 Loss -  0.7041526092673274
Epoch -  3 Loss -  0.7039914991601176
Epoch -  4 Loss -  0.7038327329626297
Epoch -  5 Loss -  0.7036762772853051
Epoch -  6 Loss -  0.703522099193322
Epoch -  7 Loss -  0.7033701662010103
Epoch -  8 Loss -  0.7032204462663166
Epoch -  9 Loss -  0.7030729077853215
Epoch -  10 Loss -  0.7029275195868052
Epoch -  11 Loss -  0.7027842509268675
Epoch -  12 Loss -  0.7026430714835951
Epoch -  13 Loss -  0.7025039513517836
Epoch -  14 Loss -  0.7023668610377061
Epoch -  15 Loss -  0.7022317714539378
Epoch -  16 Loss -  0.7020986539142272
Epoch -  17 Loss -  0.7019674801284207
Epoch -  18 Loss -  0.7018382221974361
Epoch -  19 Loss -  0.7017108526082894
Epoch -  20 Loss -  0.7015853442291692
Epoch -  21 Loss -  0.7014616703045645
Epoch -  22 Loss -  0.7013398044504398
Epoch -  23 Loss -  0.7012197206494629
Epoch -  24 Loss -  0.7011013932462812
Epoch -  25 Loss -  0.7009847969428487
Epoch -  26 Loss -  0.7008699067938

{'W1': array([[0.10001546, 0.10002374],
        [0.10001546, 0.10002374]]),
 'b1': array([[1.09379987e-06],
        [1.09388257e-06]]),
 'W2': array([[0.06892709],
        [0.06892709]]),
 'b2': array([[0.06897194]])}

# With Keras 

In [7]:
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [8]:
model=Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.get_weights()

[array([[ 0.48569965, -0.44668323],
        [-0.75351715,  0.39725375]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.1274697 ],
        [-0.83344483]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
model.set_weights([np.array([[0.1 ,  0.1 ],
        [ 0.1, 0.1 ]], dtype='float32'),
 np.array([0., 0.], dtype='float32'),
 np.array([[0.1],
        [0.1]], dtype='float32'),
 np.array([0.], dtype='float32')])

In [12]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer,loss='binary_crossentropy')

In [15]:
X = df[['cgpa', 'iq']]
y = df[['placement']]
history=model.fit(X,y,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
100/100 [==============================] - 0s 3ms/step - loss: 0.6940
Epoch 2/50
100/100 [==============================] - 0s 2ms/step - loss: 0.6933
Epoch 3/50
100/100 [==============================] - 0s 2ms/step - loss: 0.6938
Epoch 4/50
100/100 [==============================] - 0s 4ms/step - loss: 0.6942
Epoch 5/50
100/100 [==============================] - 0s 2ms/step - loss: 0.6939
Epoch 6/50
100/100 [==============================] - 0s 3ms/step - loss: 0.6934
Epoch 7/50
100/100 [==============================] - 0s 4ms/step - loss: 0.6934
Epoch 8/50
100/100 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 9/50
100/100 [==============================] - 0s 3ms/step - loss: 0.6940
Epoch 10/50
100/100 [==============================] - 0s 2ms/step - loss: 0.6940
Epoch 11/50
100/100 [==============================] - 0s 2ms/step - loss: 0.6936
Epoch 12/50
100/100 [==============================] - 0s 3ms/step - loss: 0.6942
Epoch 13/50
100/100 [====

In [16]:
model.get_weights()

[array([[0.35064086, 0.35064086],
        [0.23422213, 0.23422213]], dtype=float32),
 array([0.14940648, 0.14940648], dtype=float32),
 array([[0.03205844],
        [0.03205844]], dtype=float32),
 array([-0.0678046], dtype=float32)]